Repository aspect-build/rules_js, pull requests merged in 2023-03, with the labels that each got.

#843 Make launcher.sh generated by js_binary more self-documenting.
  js/private/js_binary.bzl
  js/private/js_binary.sh.tpl
  js/private/test/shellcheck_launcher.sh
Labels: enhancement, changes requested, in review

#900 fix: add support for local `node_toolchain`
  js/private/coverage/coverage.sh.tpl
  js/private/coverage/merger.bzl
  js/private/js_binary.bzl
  js/private/js_binary.sh.tpl
  js/private/test/shellcheck_launcher.sh
Labels: bug

#927 fix: abortcontroller is missing on node14
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  .github/workflows/ci.yaml
  e2e/worker/.bazeliskrc
  e2e/worker/.bazelrc
  e2e/worker/.bazelversion
  e2e/worker/BUILD.bazel
  e2e/worker/MODULE.bazel
  e2e/worker/WORKSPACE
  e2e/worker/defs.bzl
  e2e/worker/dummy_worker.js
  js/private/worker/src/BUILD.bazel
  js/private/worker/src/index.ts
  js/private/worker/src/package.json
  js/private/worker/worker.js
  npm/private/test/repositories_checked.bzl
  pnpm-lock.yaml
Labels: bug

#936 feat: add grant_sandbox_write_permissions attribute to js_run_devserver
  docs/js_run_devserver.md
  e2e/js_run_devserver/multirun_test.sh
  e2e/js_run_devserver/src/BUILD.bazel
  e2e/js_run_devserver/src/naughty.js
  e2e/js_run_devserver/test.sh
  js/private/js_run_devserver.bzl
  js/private/js_run_devserver.mjs
Labels: enhancement
